

// create a new user
# POST http://localhost:4000/users
# Content-Type: application/json

# {
#   "id": 30,
#   "name": "John Doe",
#   "email": "example@gmail",
#   "age": 30,
#   "city": "New York",
#   "country": "USA",
#   "isPremium": true
# }
 // get all users
# GET http://localhost:4000/users
// get user by id
# GET http://localhost:4000/users/1
// update user by id
# PUT http://localhost:4000/users/1
# Content-Type: application/json

# {
#   "name": "John Doe",
#   "email": "example@gmail.com",
#   "age": 32,
#   "city": "New York",
#   "country": "USA",
#   "isPremium": true
# }
// delete user by id
# DELETE http://localhost:4000/users/30




